LIST_THING = [
    {'thing_name': 'Кольцо защиты',
     'thing_protection': 0.02,
     'thing_attack': 0,
     'thing_hit_points': 0},
    {'thing_name': 'Перчатки',
     'thing_protection': 0.05,
     'thing_attack': 0,
     'thing_hit_points': 0},
    {'thing_name': 'Поножи',
     'thing_protection': 0.07,
     'thing_attack': 0,
     'thing_hit_points': 0},
    {'thing_name': 'Латы',
     'thing_protection': 0.1,
     'thing_attack': 0,
     'thing_hit_points': 0},
    {'thing_name': 'Точильный камень',
     'thing_protection': 0,
     'thing_attack': 0.01,
     'thing_hit_points': 0},
    {'thing_name': 'Яд Эндриага',
     'thing_protection': 0,
     'thing_attack': 0.02,
     'thing_hit_points': 0},
    {'thing_name': 'Клинок Ами',
     'thing_protection': 0,
     'thing_attack': 0.4,
     'thing_hit_points': 0},
    {'thing_name': 'Сон дракона',
     'thing_protection': 0,
     'thing_attack': 0.05,
     'thing_hit_points': 0}]
