class Armory():

    def __init__(self):
        self.armory = {'first_aid_kit': {'none': {'name': None,
                                                  'defence_boost': 0,
                                                  'attack_boost': 0,
                                                  'life_boost': 0,
                                                  'life_time': 1000,
                                                  'can_be_stolen': 0},
                                         'min': {'name': 'Minimum',
                                                 'defence_boost': 0,
                                                 'attack_boost': 0,
                                                 'life_boost': 10,
                                                 'life_time': 1000,
                                                 'can_be_stolen': True},
                                         'mid': {'name': 'Medium',
                                                 'defence_boost': 0,
                                                 'attack_boost': 0,
                                                 'life_boost': 15,
                                                 'life_time': 1000,
                                                 'can_be_stolen': True},
                                         'max': {'name': 'Maximum',
                                                 'defence_boost': 0,
                                                 'attack_boost': 0,
                                                 'life_boost': 25,
                                                 'life_time': 1000,
                                                 'can_be_stolen': True},
                                         'extra': {'name': 'Extra',
                                                   'defence_boost': 0,
                                                   'attack_boost': 0,
                                                   'life_boost': 50,
                                                   'life_time': 1000,
                                                   'can_be_stolen': False}},

                       'armour': {'none': {'name': None,
                                           'defence_boost': 0,
                                           'attack_boost': 0,
                                           'life_boost': 0,
                                           'life_time': 0,
                                           'can_be_stolen': 0},
                                  'min': {'name': 'Minimum',
                                          'defence_boost': 0.02,
                                          'attack_boost': 0,
                                          'life_boost': 0,
                                          'life_time': 10,
                                          'can_be_stolen': True},
                                  'mid': {'name': 'Medium',
                                          'defence_boost': 0.04,
                                          'attack_boost': 0,
                                          'life_boost': 0,
                                          'life_time': 15,
                                          'can_be_stolen': True},
                                  'max': {'name': 'Maximum',
                                          'defence_boost': 0.06,
                                          'attack_boost': 0,
                                          'life_boost': 0,
                                          'life_time': 20,
                                          'can_be_stolen': True},
                                  'extra': {'name': 'Extra',
                                            'defence_boost': 0.1,
                                            'attack_boost': 0,
                                            'life_boost': 0,
                                            'life_time': 1000,
                                            'can_be_stolen': False}},

                       'fire_arms': {'none': {'name': None,
                                              'defence_boost': 0,
                                              'attack_boost': 0,
                                              'life_boost': 0,
                                              'life_time': 0,
                                              'can_be_stolen': 0},
                                     'min': {'name': 'Minimum',
                                             'defence_boost': 0,
                                             'attack_boost': 1,
                                             'life_boost': 0,
                                             'life_time': 10,
                                             'can_be_stolen': True},
                                     'mid': {'name': 'Medium',
                                             'defence_boost': 0,
                                             'attack_boost': 0.2,
                                             'life_boost': 0,
                                             'life_time': 2,
                                             'can_be_stolen': True},
                                     'max': {'name': 'Maximum',
                                             'defence_boost': 0,
                                             'attack_boost': 10,
                                             'life_boost': 0,
                                             'life_time': 3,
                                             'can_be_stolen': True},
                                     'extra': {'name': 'Extra',
                                               'defence_boost': 0,
                                               'attack_boost': 5,
                                               'life_boost': 0,
                                               'life_time': 30,
                                               'can_be_stolen': False}},

                       'steel_arms': {'none': {'name': None,
                                               'defence_boost': 0,
                                               'attack_boost': 0,
                                               'life_boost': 0,
                                               'life_time': 1000,
                                               'can_be_stolen': 0},
                                      'min': {'name': 'Minimum',
                                              'defence_boost': 0,
                                              'attack_boost': 0.1,
                                              'life_boost': 0,
                                              'life_time': 1000,
                                              'can_be_stolen': True},
                                      'mid': {'name': 'Medium',
                                              'defence_boost': 0,
                                              'attack_boost': 0.5,
                                              'life_boost': 0,
                                              'life_time': 1000,
                                              'can_be_stolen': True},
                                      'max': {'name': 'Maximum',
                                              'defence_boost': 0,
                                              'attack_boost': 1,
                                              'life_boost': 0,
                                              'life_time': 1000,
                                              'can_be_stolen': True},
                                      'extra': {'name': 'Extra',
                                                'defence_boost': 0,
                                                'attack_boost': 2,
                                                'life_boost': 0,
                                                'life_time': 1000,
                                                'can_be_stolen': False}
                                      }
                       }
